--The Winged Dragon of Ra
function c51100236.initial_effect(c)
	--Summon with 3 Tribute
	c:SetUniqueOnField(1,1,51100236)
	local e1=Effect.CreateEffect(c)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_LIMIT_SUMMON_PROC)
	e1:SetCondition(c51100236.sumoncon)
	e1:SetOperation(c51100236.sumonop)
	e1:SetValue(SUMMON_TYPE_ADVANCE)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_LIMIT_SET_PROC)
	e2:SetCondition(c51100236.setcon)
	c:RegisterEffect(e2)
	--Cannot be Set
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_CANNOT_TURN_SET)
	e3:SetRange(LOCATION_MZONE)
	e3:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e3:SetTarget(c51100236.tgset)
	c:RegisterEffect(e3)
	--Summon Cannot be Negated
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_SINGLE)
	e4:SetCode(EFFECT_CANNOT_DISABLE_SUMMON)
	e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	c:RegisterEffect(e4)
	--Summon Success: Effects of non-DIVINE monsters Cannot be Activated
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e5:SetCode(EVENT_SUMMON_SUCCESS)
	e5:SetOperation(c51100236.sumsuc)
	c:RegisterEffect(e5)
 	--Original ATK/DEF
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_SINGLE)
	e6:SetCode(EFFECT_MATERIAL_CHECK)
	e6:SetValue(c51100236.valcheck)
	c:RegisterEffect(e6)
	local e7=Effect.CreateEffect(c)
	e7:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e7:SetCode(EVENT_SUMMON_SUCCESS)
	e7:SetOperation(c51100236.atkdefop)
	c:RegisterEffect(e7)
	--Cannot be Tributed by Opponent
	local e8=Effect.CreateEffect(c)
	e8:SetType(EFFECT_TYPE_SINGLE)
	e8:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e8:SetRange(LOCATION_MZONE)
	e8:SetCode(EFFECT_UNRELEASABLE_SUM)
	e8:SetValue(c51100236.tgvalue)
	c:RegisterEffect(e8)
    --Cannot Switch Controller
	local e9=Effect.CreateEffect(c)
	e9:SetType(EFFECT_TYPE_SINGLE)
	e9:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e9:SetRange(LOCATION_MZONE)
	e9:SetCode(EFFECT_CANNOT_CHANGE_CONTROL)
	c:RegisterEffect(e9)
	--Cannot be Target
	local e10=Effect.CreateEffect(c)
	e10:SetType(EFFECT_TYPE_SINGLE)
	e10:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e10:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e10:SetRange(LOCATION_MZONE)
	e10:SetValue(1)
	c:RegisterEffect(e10)
    --Cannot be Destroyed by Card Effect
	local e11=Effect.CreateEffect(c)
	e11:SetType(EFFECT_TYPE_SINGLE)
	e11:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e11:SetRange(LOCATION_MZONE)
	e11:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	e11:SetValue(1)
	c:RegisterEffect(e11)
	--Cannot be Removed
	local e12=Effect.CreateEffect(c)
	e12:SetType(EFFECT_TYPE_SINGLE)
	e12:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e12:SetRange(LOCATION_MZONE)
	e12:SetCode(EFFECT_CANNOT_REMOVE)
	c:RegisterEffect(e12)
	--Cannot Send to Grave
	local e13=Effect.CreateEffect(c)
	e13:SetType(EFFECT_TYPE_SINGLE)
	e13:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e13:SetRange(LOCATION_MZONE)
	e13:SetCode(EFFECT_CANNOT_TO_GRAVE)
	c:RegisterEffect(e13)
	--Cannot Return to Hand
	local e14=Effect.CreateEffect(c)
	e14:SetType(EFFECT_TYPE_SINGLE)
	e14:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e14:SetRange(LOCATION_MZONE)
	e14:SetCode(EFFECT_CANNOT_TO_HAND)
	c:RegisterEffect(e14)
	--Cannot Return to Deck
	local e15=Effect.CreateEffect(c)
	e15:SetType(EFFECT_TYPE_SINGLE)
	e15:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e15:SetRange(LOCATION_MZONE)
	e15:SetCode(EFFECT_CANNOT_TO_DECK)
	c:RegisterEffect(e15)
	--Change Battle Position in Turn that is Normal Summoned
	local e16=Effect.CreateEffect(c)
	e16:SetDescription(aux.Stringid(51100236,0))
	e16:SetCategory(CATEGORY_POSITION)
	e16:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e16:SetType(EFFECT_TYPE_IGNITION)
	e16:SetRange(LOCATION_MZONE)
	e16:SetCountLimit(1)
	e16:SetCost(c51100236.cbpcost)
	e16:SetOperation(c51100236.cbpop)
	c:RegisterEffect(e16)
	--
	local e17=Effect.CreateEffect(c)
	e17:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e17:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e17:SetCode(EVENT_SUMMON_SUCCESS)
	e17:SetOperation(c51100236.cbpop2)
	c:RegisterEffect(e17)
	--If Special Summoned: Send to Grave
	local e18=Effect.CreateEffect(c)
	e18:SetDescription(aux.Stringid(51100236,0))
	e18:SetCategory(CATEGORY_TOGRAVE)
	e18:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e18:SetRange(LOCATION_MZONE)
	e18:SetProperty(EFFECT_FLAG_REPEAT+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e18:SetCountLimit(1)
	e18:SetCode(EVENT_PHASE+PHASE_END)
	e18:SetCondition(c51100236.stgcon)
	e18:SetTarget(c51100236.stgtg)
	e18:SetOperation(c51100236.stgop)
	c:RegisterEffect(e18)
	--Change Battle Target when Special Summoned in Defense Position
	local e19=Effect.CreateEffect(c)
	e19:SetDescription(aux.Stringid(51100236,0))
	e19:SetProperty(EFFECT_FLAG_NO_TURN_RESET)
	e19:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e19:SetCode(EVENT_BE_BATTLE_TARGET)
	e19:SetRange(LOCATION_MZONE)
	e19:SetCountLimit(1)
	e19:SetCondition(c51100236.cbtcon)
	e19:SetOperation(c51100236.cbtop)
	c:RegisterEffect(e19)
	--Point-to-Point Transfer
	local e20=Effect.CreateEffect(c)
	e20:SetDescription(aux.Stringid(51100236,1))
	e20:SetCategory(CATEGORY_ATKCHANGE)
	e20:SetType(EFFECT_TYPE_QUICK_O)
	e20:SetCode(EVENT_FREE_CHAIN)
	e20:SetHintTiming(TIMING_DAMAGE_STEP)
	e20:SetRange(LOCATION_MZONE)
	e20:SetCost(c51100236.ptpcost)
	e20:SetOperation(c51100236.ptpop)
	c:RegisterEffect(e20)
	--Tribute-to-Point Transfer
	local e21=Effect.CreateEffect(c)
	e21:SetDescription(aux.Stringid(51100236,2))
	e21:SetCategory(CATEGORY_ATKCHANGE)
	e21:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_QUICK_O)
	e21:SetCode(EVENT_FREE_CHAIN)
	e21:SetHintTiming(TIMING_DAMAGE_STEP)
	e21:SetRange(LOCATION_MZONE)
	e21:SetCost(c51100236.ttpcost)
	e21:SetOperation(c51100236.ttpop)
	c:RegisterEffect(e21)
	--Instant Attack
	local e22=Effect.CreateEffect(c)
	e22:SetDescription(aux.Stringid(51100236,3))
	e22:SetType(EFFECT_TYPE_QUICK_O)
	e22:SetCode(EVENT_FREE_CHAIN)
	e22:SetHintTiming(TIMING_BATTLE_PHASE)
	e22:SetRange(LOCATION_MZONE)
	e22:SetCountLimit(1)
	e22:SetCost(c51100236.iacost)
	e22:SetOperation(c51100236.iaop)
	c:RegisterEffect(e22)
	--"De-Fusion" Point-to-Point Transfer reverse
	local e23=Effect.CreateEffect(c)
	e23:SetDescription(aux.Stringid(51100236,4))
	e23:SetCategory(CATEGORY_RECOVER+CATEGORY_ATKCHANGE)
	e23:SetType(EFFECT_TYPE_QUICK_O)
	e23:SetCode(EVENT_FREE_CHAIN)
	e23:SetHintTiming(TIMING_DAMAGE_STEP)
	e23:SetRange(LOCATION_MZONE)
	e23:SetCountLimit(1)
	e23:SetCost(c51100236.defusicost)
	e23:SetOperation(c51100236.defusiop)
	c:RegisterEffect(e23)
	--Egyptian God Phoenix
	local e24=Effect.CreateEffect(c)
	e24:SetDescription(aux.Stringid(51100236,5))
	e24:SetCategory(CATEGORY_TOKEN)
	e24:SetType(EFFECT_TYPE_QUICK_O)
	e24:SetCode(EVENT_FREE_CHAIN)
	e24:SetHintTiming(TIMING_DAMAGE_STEP)
	e24:SetRange(LOCATION_MZONE)
	e24:SetCountLimit(1)
	e24:SetCost(c51100236.egpcost)
	e24:SetOperation(c51100236.egpop)
	c:RegisterEffect(e24)
	--ATK/DEF effects are only applied until the End Phase
	local e25=Effect.CreateEffect(c)
	e25:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e25:SetProperty(EFFECT_FLAG_REPEAT)
	e25:SetRange(LOCATION_MZONE)
	e25:SetCode(EVENT_PHASE+PHASE_END)
	e25:SetCountLimit(1)
	e25:SetOperation(c51100236.atkdefresetop)
	c:RegisterEffect(e25)
end
function c51100236.valcheck(e,c)
	local g=c:GetMaterial()
	Original_ATK=g:GetSum(Card.GetAttack)
	Original_DEF=g:GetSum(Card.GetDefence)
end
function c51100236.atkdefop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:GetMaterialCount()==0 then return end
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_SET_BASE_ATTACK)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetValue(Original_ATK)
	e1:SetReset(RESET_EVENT+0x1fe0000)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_SET_BASE_DEFENCE)
	e2:SetValue(Original_DEF)
	c:RegisterEffect(e2)
end
function c51100236.sumoncon(e,c)
	if c==nil then return true end
	return Duel.GetLocationCount(c:GetControler(),LOCATION_MZONE)>-3 and Duel.GetTributeCount(c)>=3
end
function c51100236.sumonop(e,tp,eg,ep,ev,re,r,rp,c)
	local g=Duel.SelectTribute(tp,c,3,3)
	c:SetMaterial(g)
	Duel.Release(g,REASON_SUMMON+REASON_MATERIAL)
end
function c51100236.setcon(e,c)
	if not c then return true end
	return false
end
function c51100236.tgset(e,c)
return c:IsAttribute(ATTRIBUTE_DEVINE)
end
function c51100236.sumsuc(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_TRIGGER)
	e1:SetRange(LOCATION_MZONE)
	e1:SetTargetRange(LOCATION_GRAVE,LOCATION_GRAVE+LOCATION_MZONE,LOCATION_MZONE+LOCATION_SZONE,LOCATION_SZONE+LOCATION_HAND,LOCATION_HAND)
	e1:SetTarget(c51100236.triggertg)
	e1:SetReset(RESET_EVENT+EVENT_SUMMON_SUCCESS)
	c:RegisterEffect(e1)
end
function c51100236.triggertg(e,c)
	return not c:IsRace(RACE_DEVINE) and not c:IsCode(3136426) and not c:IsCode(82732705) and not c:IsCode(72302403) and not c:IsCode(44656491) and not c:IsCode(85101228) 
	and not c:IsCode(12923641) and not c:IsCode(93087299) and not c:IsCode(85742772) and not c:IsCode(50045299) and not c:IsCode(52503575) and not c:IsCode(23950192) 
	and not c:IsCode(82498947) and not c:IsCode(63519819) and not c:IsCode(80233946) and not c:IsCode(100000240) and not c:IsCode(83965310)
end
function c51100236.tgvalue(e,re,rp)
local c=e:GetHandler()
 return not c:IsControler(tp)
end
function c51100236.cbpcost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return e:GetHandler():GetFlagEffect(51100236)==1 and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_NORMAL)==SUMMON_TYPE_NORMAL 
	and e:GetHandler():GetAttackAnnouncedCount()==0 end
end
function c51100236.cbpop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	Duel.ChangePosition(c,POS_FACEUP_DEFENCE,0,POS_FACEUP_ATTACK,0)
end
function c51100236.cbpop2(e,tp,eg,ep,ev,re,r,rp)
	e:GetHandler():RegisterFlagEffect(51100236,RESET_EVENT+0xfc0000+RESET_PHASE+PHASE_END,0,1)
end
function c51100236.stgcon(e,tp,eg,ep,ev,re,r,rp)
	return bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL
end
function c51100236.stgtg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return true end
	Duel.SetOperationInfo(0,CATEGORY_TOGRAVE,e:GetHandler(),1,0,0)
end
function c51100236.stgop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:IsRelateToEffect(e) and c:IsFaceup() then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_DISABLE)
		e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e1)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_DISABLE_EFFECT)
		e2:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e2)
		Duel.BreakEffect()
		Duel.SendtoGrave(c,REASON_EFFECT)
	end
end
function c51100236.cbtcon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local bt=Duel.GetAttackTarget()
	return c~=bt and bt:IsControler(tp) and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL and e:GetHandler():IsDefencePos()
end
function c51100236.cbtop(e,tp,eg,ep,ev,re,r,rp)
	Duel.ChangeAttackTarget(e:GetHandler())
end
function c51100236.ptpcost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetFlagEffect(tp,511000237)==0 and Duel.GetLP(tp)>1 
	and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL end
	Duel.RegisterFlagEffect(tp,51100237,RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END+RESET_SELF_TURN,0,1)
end
function c51100236.ptpop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local LP=Duel.GetLP(tp)
	Duel.SetLP(tp,1)
	ATK=LP-1
	DEF=LP-1
	if c:IsFaceup() and c:IsRelateToEffect(e) then
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_SET_BASE_ATTACK)
	e1:SetValue(ATK+c:GetAttack())
	e1:SetReset(RESET_EVENT+0x1ff0000)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_SET_BASE_DEFENCE)
	e2:SetValue(DEF+c:GetDefence())
	c:RegisterEffect(e2)
	end
end
function c51100236.ttpcost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.CheckReleaseGroup(tp,nil,1,e:GetHandler()) and Duel.GetFlagEffect(tp,51100237)==1 
	and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL end
end
function c51100236.ttpop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local g=Duel.SelectReleaseGroup(tp,nil,4,4,e:GetHandler())
	local ATK=g:GetSum(Card.GetAttack)
	local DEF=g:GetSum(Card.GetDefence)
	Duel.Release(g,REASON_COST)
	if c:IsFaceup() and c:IsRelateToEffect(e) then
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_SET_BASE_ATTACK)
	e1:SetValue(ATK+c:GetAttack())
	e1:SetReset(RESET_EVENT+0x1ff0000)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_SET_BASE_DEFENCE)
	e2:SetValue(DEF+c:GetDefence())
	c:RegisterEffect(e2)
	end
end
function c51100236.costfilter(c)
	return c:IsCode(95286165) and c:IsAbleToGraveAsCost()
end
function c51100236.defusicost(e,tp,eg,ep,ev,re,r,rp,chk)
		if chk==0 then return Duel.IsExistingMatchingCard(c51100236.costfilter,tp,LOCATION_HAND+LOCATION_SZONE,0,1,e:GetHandler()) and Duel.GetFlagEffect(tp,51100237)==1 
		and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL and e:GetHandler():GetAttack()>0 end
		Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TOGRAVE)
		local g=Duel.SelectMatchingCard(tp,c51100236.costfilter,tp,LOCATION_HAND+LOCATION_SZONE,0,1,1,nil)
		Duel.SendtoGrave(g,REASON_COST)
end
function c51100236.defusiop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:IsFaceup() and c:IsRelateToEffect(e) then
		local ATK=c:GetAttack()
		local DEF=c:GetDefence()
		Duel.Recover(tp,ATK,REASON_EFFECT)
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetReset(RESET_EVENT+0x1fe0000)
		e1:SetCode(EFFECT_SET_BASE_ATTACK)
		e1:SetValue(-ATK)
		c:RegisterEffect(e1)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_SET_BASE_DEFENCE)
		e2:SetValue(-DEF)
		c:RegisterEffect(e2)
		end
		if Duel.GetAttacker()==e:GetHandler() then
		Duel.NegateAttack()
	end
end
function c51100236.iacost(e,tp,eg,ep,ev,re,r,rp,chk)
	local c=e:GetHandler()
	if chk==0 then return e:GetHandler():GetAttackAnnouncedCount()==0 and Duel.GetFlagEffect(tp,51100237)==1 and Duel.GetFlagEffect(tp,511000236)==0 
	and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL end
	Duel.RegisterFlagEffect(tp,511000236,RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END+RESET_SELF_TURN,0,1)
	end
function c51100236.iaop(e,tp,eg,ep,ev,re,r,rp)
		local c=e:GetHandler()
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_EXTRA_ATTACK)
		e1:SetReset(RESET_EVENT+0x1ff0000)
		e1:SetValue(99)
		c:RegisterEffect(e1)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_CANNOT_ATTACK)
		e2:SetCondition(c51100236.atkcon)
		c:RegisterEffect(e2)
		local e3=Effect.CreateEffect(c)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e3:SetRange(LOCATION_MZONE)
		e3:SetCode(EFFECT_IMMUNE_EFFECT)
		e3:SetReset(RESET_EVENT+0x1ff0000)
		e3:SetValue(1)
		c:RegisterEffect(e3)
		if Duel.GetTurnPlayer()~=tp then
		local e4=Effect.CreateEffect(c)
		e4:SetType(EFFECT_TYPE_SINGLE)
		e4:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e4:SetRange(LOCATION_MZONE)
		e4:SetCode(EFFECT_CANNOT_TRIGGER)
		e4:SetTarget(c51100236.iatrig)
		e4:SetReset(RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e4)
		local e5=Effect.CreateEffect(c)
		e5:SetType(EFFECT_TYPE_FIELD)
		e5:SetRange(LOCATION_MZONE)
		e5:SetCode(EFFECT_CANNOT_ATTACK_ANNOUNCE)
		e5:SetTargetRange(LOCATION_MZONE,0)
		e5:SetTarget(c51100236.notattackannouce)
		e5:SetReset(RESET_EVENT+0x1ff0000)
		c:RegisterEffect(e5)
		local e6=Effect.CreateEffect(c)
		e6:SetType(EFFECT_TYPE_FIELD)
		e6:SetCode(EFFECT_CANNOT_M2)
		e6:SetRange(LOCATION_MZONE)
		e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_OATH)
		e6:SetTargetRange(1,0)
		e6:SetReset(RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END+RESET_SELF_TURN)
		Duel.RegisterEffect(e6,tp)
		if Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_DRAW or Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_STANDBY then
		Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		end
		if Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_MAIN1 then
		Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_STANDBY,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		end
		if Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_BATTLE then
		Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_STANDBY,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
		end
		if Duel.GetTurnPlayer()~=tp and Duel.GetCurrentPhase()==PHASE_MAIN2 then
		Duel.SkipPhase(1-tp,PHASE_DRAW,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_STANDBY,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_MAIN1,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_BATTLE,RESET_PHASE+PHASE_END+RESET_OPPO_TURN,2)
		Duel.SkipPhase(1-tp,PHASE_MAIN2,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_STANDBY,RESET_PHASE+PHASE_END,1)
		Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
	end
	end
end
function c51100236.atkcon(e)
	return e:GetHandler():IsDirectAttacked()
end
function c51100236.iatrig(e,c)
	return e:GetHandler()
end
function c51100236.notattackannouce(e,c)
	return c~=e:GetHandler()
end
function c51100236.egpcost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetFlagEffect(tp,51100237)==0  and bit.band(e:GetHandler():GetSummonType(),SUMMON_TYPE_SPECIAL)==SUMMON_TYPE_SPECIAL end
	Duel.RegisterFlagEffect(tp,511000237,RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END+RESET_SELF_TURN,0,1)
end
function c51100236.egpop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if c:IsRelateToEffect(e) and c:IsFaceup() then
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_DISABLE)
		e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e1)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_DISABLE_EFFECT)
		e2:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		c:RegisterEffect(e2)
		Duel.BreakEffect()
		Duel.SendtoGrave(c,REASON_EFFECT)
		if Duel.GetLocationCount(tp,LOCATION_MZONE)<1 then return end
		if not Duel.IsPlayerCanSpecialSummonMonster(tp,511000237,0,0x21,0,0,10,RACE_DEVINE,ATTRIBUTE_DEVINE) then return end
		for i=1,1 do
		local token=Duel.CreateToken(tp,511000236+i)
		Duel.SpecialSummonStep(token,0,tp,tp,false,false,POS_FACEUP_ATTACK)
		local e3=Effect.CreateEffect(e:GetHandler())
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e3:SetRange(LOCATION_MZONE)
		e3:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
		e3:SetValue(1)
		e3:SetReset(RESET_EVENT+0x1ff0000+RESET_PHASE+PHASE_END)
		token:RegisterEffect(e3,true)
		local e4=e3:Clone()
		e4:SetCode(EFFECT_AVOID_BATTLE_DAMAGE)
		token:RegisterEffect(e4,true)
		local e5=e3:Clone()
		e5:SetCode(EFFECT_IMMUNE_EFFECT)
		token:RegisterEffect(e5,true)
		local e6=Effect.CreateEffect(e:GetHandler())
		e6:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e6:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e6:SetRange(LOCATION_MZONE)
		e6:SetCode(EVENT_PHASE+PHASE_END)
		e6:SetCountLimit(1)
		e6:SetOperation(c51100236.egpendop)
		token:RegisterEffect(e6,true)
		--Incinerate
		local e7=Effect.CreateEffect(e:GetHandler())
		e7:SetDescription(aux.Stringid(51100236,0))
		e7:SetCategory(CATEGORY_DISABLE+CATEGORY_DESTROY)
		e7:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_IGNORE_IMMUNE)
		e7:SetType(EFFECT_TYPE_QUICK_O)
		e7:SetCode(EVENT_FREE_CHAIN)
		e7:SetHintTiming(TIMING_DAMAGE_STEP)
		e7:SetRange(LOCATION_MZONE)
		e7:SetCountLimit(1)
		e7:SetCost(c51100236.inccost)
		e7:SetTarget(c51100236.inctg)
		e7:SetOperation(c51100236.incop)
		token:RegisterEffect(e7)
	end
	Duel.SpecialSummonComplete()
end
end
function c51100236.egpendop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_SELF_DESTROY)
	c:RegisterEffect(e1)
end
function c51100236.inccost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.CheckLPCost(tp,1000) end
	Duel.PayLPCost(tp,1000)
end
function c51100236.inctg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chk==0 then return Duel.IsExistingTarget(Card.IsDestructable,tp,0,LOCATION_MZONE,1,nil) end
	local g=Duel.GetMatchingGroup(Card.IsDestructable,tp,0,LOCATION_MZONE,nil)
	Duel.SetOperationInfo(0,CATEGORY_DESTROY,g,g:GetCount(),0,0)
end
function c51100236.incop(e,tp,eg,ep,ev,re,r,rp)
		local c=e:GetHandler()
		local g=Duel.GetMatchingGroup(Card.IsDestructable,tp,0,LOCATION_MZONE,nil)
		local tc=g:GetFirst()
		while tc do
		local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_DISABLE)
		e1:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		tc:RegisterEffect(e1)
		local e2=Effect.CreateEffect(c)
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_DISABLE_EFFECT)
		e2:SetReset(RESET_EVENT+0x1fe0000+RESET_PHASE+PHASE_END)
		tc:RegisterEffect(e2)
		tc=g:GetNext()
		Duel.BreakEffect()
		Duel.Destroy(g,REASON_EFFECT)
	end
end
function c51100236.atkdefresetop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_SET_ATTACK_FINAL)
	e1:SetValue(c:GetBaseAttack())
	e1:SetReset(RESET_EVENT+0x1fe0000)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_SET_DEFENCE_FINAL)
	e2:SetValue(c:GetBaseDefence())
	e2:SetReset(RESET_EVENT+0x1fe0000)
	c:RegisterEffect(e2)
end
